---
#title: "Lewisham Cycle Parking"
#author: "Jorge Martínez López <jorgeml@jorgeml.me>"
#date: "09/07/2020"
license: GPLv3
output: 
  html_document:
    toc: false
    toc_float:
      collapsed: true
      smooth_scroll: true
mainfont: Open Sans
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("dplyr")
library("osmdata")
library("htmltools")
library("sf")
library("leaflet")
library("leaflet.extras")
```

```{r, main, include=FALSE, warning=FALSE}

boundary_box <-
  getbb ('London Borough of Lewisham', format_out = 'polygon')

parking <- opq(bbox = boundary_box) %>%
  add_osm_feature(key = 'amenity', value = 'bicycle_parking') %>%
  add_osm_feature (key = "access", value = "!private") %>%
  osmdata_sf () %>%
  trim_osmdata (boundary_box)

parking$osm_points <- parking$osm_points %>%
  dplyr::mutate(label = paste0(
    htmlEscape(parking$osm_points$bicycle_parking),
    " (",
    htmlEscape(parking$osm_points$capacity),
    ")"
  ))

parking$osm_points <- parking$osm_points %>%
  dplyr::mutate(
    popup = paste0(
      "<b>Cycle Parking</b><br/>",
      "Type: ",
      htmlEscape(parking$osm_points$bicycle_parking),
      "<br/>",
      "Capacity: ",
      htmlEscape(parking$osm_points$capacity),
      "<br/>",
      "Covered: ",
      htmlEscape(parking$osm_points$covered),
      "<br/>",
      "Access: ",
      htmlEscape(parking$osm_points$access),
      "<br/>",
      "Supervised: ",
      htmlEscape(parking$osm_points$supervised),
      "<br/>",
      "Description: ",
      htmlEscape(parking$osm_points$description)
      
    )
  )

cycleway <- opq(bbox = boundary_box) %>%
  add_osm_feature(key = 'highway', value = 'cycleway') %>%
  osmdata_sf() %>%
  trim_osmdata (boundary_box)

# cycleway$osm_lines <- cycleway$osm_lines %>%
#   dplyr::mutate(label = paste0(htmlEscape(cycleway$osm_lines['name'])))
# 
# cycleway$osm_lines <- cycleway$osm_lines %>% 
#   dplyr::mutate(popup = paste0(
#     "<b>Cycleway</b><br/>",
#        "Name: ",
#        htmlEscape(cycleway$osm_lines$name),
#        "<br/>",
#        "Cycleway: ",
#        htmlEscape(cycleway$osm_lines$cycleway),
#        "<br/>",
#        "Lit: ",
#        htmlEscape(cycleway$osm_lines$lit),
#        "<br/>",
#        "Segregated: ",
#        htmlEscape(cycleway$osm_lines$segregated),
#        "<br/>",
#        "Surface: ",
#        htmlEscape(cycleway$osm_lines$surface),
#       "<br/>",
#        "Description: ",
#        htmlEscape(cycleway$osm_lines$description)
#     
#      ) )

```

```{r, map, echo=FALSE, message=FALSE, warning=FALSE}

getColor <- function(parkingpoints) {
  sapply(parkingpoints$covered, function(covered) {
    if (is.na(covered)) {
      "darkred"
    } else if (covered == "yes") {
      "green"
    } else if (covered == "partial") {
      "orange"
    } else if (covered == "no") {
      "red"
    } else {
      "cadetblue"
    }
  })
}

icons <- awesomeIcons(
  icon = "bicycle",
  iconColor = "lightgray",
  library = "fa",
  markerColor = as.character(getColor(parking$osm_points)),
  spin = FALSE,
  extraClasses = NULL,
  squareMarker = TRUE,
  iconRotate = 0,
  fontFamily = "sans",
  text = parking$osm_points$capacity
)

parking$osm_points %>%
  leaflet(height = "800px", width = "100%") %>%
  setView(lat = 51.4536,
          lng = -0.0180,
          zoom = 13) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addAwesomeMarkers(
    icon = icons,
    label = parking$osm_points$label,
    popup = parking$osm_points$popup,
  ) %>%
  addPolylines(data = cycleway$osm_lines, opacity = 0.2) %>%
  leaflet.extras::addResetMapButton() %>%
  leaflet.extras::addControlGPS(
    options = gpsOptions(
      position = "topright",
      activate = FALSE,
      autoCenter = TRUE,
      maxZoom = NULL,
      setView = TRUE
    )
  )

```
